Add isRecoverable flag & add test
teamstarter/graphql-node-jobs pull request #33
Opened 2021-05-18 09:56 UTC by germainvictor

2021-05-18 09:56 UTC, germainvictor commented
https://linear.app/teamstarter/issue/TEA-450/allow-to-flag-jobs-as-recoverable

2021-05-19 11:55 UTC, vincentdesmares requested changes
Les tests ne passent pas

2021-05-20 08:01 UTC, vincentdesmares requested changes

2021-05-20 08:01 UTC, vincentdesmares commented on src/graphql/job/recover.ts
> +    description: 'Allows a job to be recoverable',
Mauvaise description. Le job est déjà authorisé à être récupérable. Ce point permet de recover un job en le remettant dans la queue avec les informations de processing déjà aquises.

2021-05-21 07:27 UTC, germainvictor commented on src/graphql/job/recover.ts
> +    description: 'Allows a job to be recoverable',
Done

2021-05-21 16:32 UTC, germainvictor commented on tests/__snapshots__/job.spec.js.snap
> +exports[`Test the job endpoint A job failed can be recover  1`] = `"[TypeError: steps.error is not a function] Stack: TypeError: steps.error is not a function"`;
Done

2021-05-21 16:36 UTC, merged