feat(workerMonitoring): add model & logic
teamstarter/graphql-node-jobs pull request #39
Opened 2021-05-27 14:08 UTC by germainvictor

https://linear.app/teamstarter/issue/TEA-547/keep-track-of-each-worker-last-call

2021-05-28 12:17 UTC, bryneTane approved these changes

2021-05-31 08:19 UTC, Azzeddine-AMRANE approved these changes

2021-06-01 08:38 UTC, vincentdesmares requested changes

2021-06-01 09:24 UTC, germainvictor commented on src/graphql/job/acquire.ts
> +        const workerMonitoring = await models.workerMonitoring.findOne({
Done

2021-06-01 09:24 UTC, germainvictor commented on migrations/20201130182919-create-workerMonitoring.js
> +        type: Sequelize.STRING,
Done

2021-06-04 13:51 UTC, merged